WIFI_SSID="your ssid"
WIFI_PASSWORD="your password"
WIFI_COUNTRY="YOUT_CONTRY_CODE"
DAYTIME_UPDATE_INTERVAL=180000 # 3 min
NIGHTTIME_UPDATE_INTERVAL=1800000 # 30 min
HISTORY_SIZE=200
LOCATION_LATITUDE=YOUR_LATITUDE
LOCATION_LONGITUDE=YOUR_LONGITUTE
SUNRISE_API="https://api.sunrise-sunset.org/json?lat="
SUNRISE_UPDATE_INTERVAL=43200000 # 12 hours
