from micropython import const

WIFI_SSID="Villa Einhorn (2,4)"
WIFI_PASSWORD="wlan@radebeul.de"
WIFI_COUNTRY="DE"
DAYTIME_UPDATE_INTERVAL=const(120) # 2 min
NIGHTTIME_UPDATE_INTERVAL=const(1200) # 20 min
DATA_UPDATE_INTERVAL=const(30) # 30 sec
HISTORY_SIZE=const(400)
LOCATION_LATITUDE=51.105
LOCATION_LONGITUDE=13.675
SUNRISE_API="https://api.sunrise-sunset.org/json?lat="
MIRROR_DISPLAY=True
ROTATE_DISPLAY=const(90)
INVERTER_IP="192.168.1.122"
INVERTER_PORT=const(8899)